### ISSUE TITLE
[BUG] title not resizing with menu

### ISSUE THREAD

**Issue by MayuSakurai** [Mineshaft-game/Mineshaft#18]
**Describe the bug**
The title does not resize with the menu

**To Reproduce**
1. Resize the window 

**Expected behavior**
It would resize with the menu

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 21.04

**Comment by leha-code** [comment]
I think I fixed that but forgot to push lemme check

**Comment by leha-code** [comment]
Yup
